// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storage

import (
	"database/sql"

	"github.com/google/uuid"
)

type Debt struct {
	ID           uuid.UUID
	FirstName    string
	LastName     string
	PhoneNumber  string
	Jshshir      int32
	Address      string
	Price        float64
	PricePaid    float64
	Acquaintance sql.NullString
	Collateral   sql.NullString
	Deadline     string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullInt32
}
